// Could add a simple to menu suchas: http://twilext.com/
// Home Features Pricing Signup Login Howto Contact Us
//
document.write('<div style="height:90px;width: 900px;position:fixed;">&nsbp.</div>');
document.write('<div id="topHeading">');
document.write('<table>');
document.write('<tr>');
document.write('<td>');
document.write('    <div class="menuicon" onclick="menuicon()">');
document.write('        <div class="bar1" onclick="menubar()"></div>');
document.write('        <div class="bar2" onclick="menubar()"></div>');
document.write('        <div class="bar3" onclick="menubar()"></div>');
document.write('        <div class="bar4" onclick="menubar()"></div>');
document.write('        <div class="bar5" onclick="menubar()"></div>');
document.write('        <div class="bar6" onclick="menubar()"></div>');
document.write('        <div class="bar6" onclick="menubar()"></div>');
document.write('    </div>');
document.write('    <div class="menuDropdown">');
document.write('        <div id="menuDropdownItems" class="menuDropdownList">');
document.write('            <a href="/pages/index.html">Home</a>');
document.write('            <a href="/pages/writing.html">Writing</a>');
document.write('            <a href="/pages/tech.html">Tech</a>');
document.write('            <a href="/pages/about.html">About</a>');
document.write('            <a href="/tigsms/index.html">SMS</a>');
document.write('            <a href="/tigsms/index.html">Voice calls</a>');
document.write('            <a href="/tigsync/docroot/index.html">Voice calls</a>');
document.write('        </div>');
document.write('    </div>');
document.write('</td>');
document.write('<td>');
document.write('    <div id="topImgLeft">');
document.write('        <a href="/pages/index.html"><img src="/images/topImgLeft.jpg" title="Tiger Farm Press logo" /></a>');
document.write('    </div>');
document.write('    <div id="topImgCenter">');
document.write('        <img src="/images/topImgCenter.jpg" alt="Tiger Farm Press"/>');
document.write('        <div id="topImgRight"><a href="/pages/about.html">Stacy David</a></div>');
document.write('    </div>');
document.write('</td>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
document.write('<div id="contentTopBuffer">&nsbp.</div>');